### ISSUE TITLE
关于“前端签名”有没有具体的例子

### ISSUE THREAD

**Issue by liuxibaba** [JCCDex/jcc_server_doc#1]

**Comment by GinMu** [comment]
前端签名参考[Signature](https://github.com/JCCDex/jcc_jingtum_lib#about-signature)

**Comment by GinMu** [comment]
交易参考[Exchange](https://github.com/JCCDex/jcc_exchange#jcc_exchange)

**Comment by liuxibaba** [comment]
Thanks
